name: kip_app
description: KIP 쇼핑몰 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 라우팅
  go_router: ^14.0.0

  # 상태관리
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP 통신
  dio: ^5.4.3
  retrofit: ^4.1.0

  # 로컬 저장소 (토큰 저장)
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # 이미지
  cached_network_image: ^3.3.1

  # UI 유틸
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  badges: ^3.1.2

  # 아이콘
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true